step yml update

diff --git a/step.yml b/step.yml
--- a/step.yml
+++ b/step.yml
@@ -2,43 +2,57 @@ title: Script
 summary: |-
   The power is in your hands. Use it wisely!
 description: |-
-  Specify the script content and (optionally) the script runner
-  binary and this step will execute it.
+  Specify the script content and (optionally) the script runner,
+  to run any custom script in your [bitrise]() workflow!
 
-  The *runner* can even be a command, if it's available in the PATH
-  and can execute the script it will work.
+  The **runner** can even be a command, as long as it's available in the `PATH`
+  and can execute the script, it will work.
 
   For example to run a [Go](https://golang.org/) Hello World "script"
   you can define the content:
 
-      package main
-      import "fmt"
-      func main() {
-          fmt.Println("hello world")
-      }
+  ```
+  package main
+  import "fmt"
+  func main() {
+      fmt.Println("Hello World")
+  }
+  ```
 
   Set the *Execute with* parameter to `go run` and specify
   a *script file path* because `go run` can only accept (at the moment)
-  files with a .go extension (just specify `step.go` as the script path).
+  files with a `.go` extension (just specify `main.go` or `step.go` as the script path).
 
-  If the `go` binary can be found in the PATH your Hello World
+  If the `go` binary can be found in the `$PATH` your Hello World
   script will run without any problem.
 website: https://github.com/bitrise-io/steps-script
 source_code_url: https://github.com/bitrise-io/steps-script
 support_url: https://github.com/bitrise-io/steps-script/issues
 host_os_tags:
-  - osx-10.10
+  - osx
+  - ubuntu
 project_type_tags: []
 type_tags:
   - script
+  - utility
 is_requires_admin_user: false
 is_always_run: false
 is_skippable: false
 inputs:
   - content: |-
       #!/bin/bash
+      # fail if any commands fails
+      set -e
+      # debug log
+      set -x
 
-      echo "Hello Bitrise!"
+      # write your script here
+      echo "Hello World!"
+
+      # or run a script from your repository, like:
+      # bash ./path/to/script.sh
+      # not just bash, e.g.:
+      # ruby ./path/to/script.rb
     opts:
       title: "Script content"
       description: |
@@ -60,7 +74,6 @@ inputs:
 
         You can even specify an execution command
         like `go run` instead of just a binary.
-      is_expand: false
       is_required: true
   - is_debug: "no"
     opts:
@@ -72,16 +85,14 @@ inputs:
         - "no"
         - "yes"
       is_expand: false
-      is_required: false
-  - working_dir:
+      is_required: true
+  - working_dir: ""
     opts:
       title: "Working directory"
       description: |
         This directory will be set as the current working
         directory for the script.
-      is_expand: true
-      is_required: false
-  - script_file_path:
+  - script_file_path: ""
     opts:
       title: "Script file path"
       description: |
@@ -97,5 +108,3 @@ inputs:
         If you specify a relative path then it will be
         relative to the *working directory* (which you
         can optinally specify as well).
-      is_expand: true
-      is_required: false
