default content update

diff --git a/step.yml b/step.yml
--- a/step.yml
+++ b/step.yml
@@ -37,6 +37,10 @@ is_skippable: false
 inputs:
   - content: |-
       #!/bin/bash
+      # fail if any commands fails
+      set -e
+      # debug log
+      set -x
 
       echo "Hello Bitrise!"
     opts:
